feat: different copy for each case

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -52,7 +52,7 @@ runs:
       run: |
         if [ -z ${{ env.PREV_HEAD_SHA }} ] || [ -z ${{ env.PREV_BASE_SHA }} ]; then
           echo ::notice:: "No previous SHAs found; behaving as if diff has changed"
-          echo HAS_DIFF="1" >> $GITHUB_ENV
+          echo NO_PREV_SHAS="1" >> $GITHUB_ENV
           exit 0
         fi
 
@@ -70,13 +70,13 @@ runs:
         fi
 
     - name: Dismiss approvals if diff has changed or if any prior step failed
-      if: job.steps.check.status == failure() || env.HAS_DIFF != '0'
+      if: job.steps.check.status == failure() || env.HAS_DIFF != '0' || env.NO_PREV_SHAS != '0'
       # TODO: remove dry-run once ready for production
       uses: withgraphite/dismiss-all-approvals-js@dry-run
       # uses: withgraphite/dismiss-all-approvals-js@main
       with:
         github-token: ${{ inputs.github-token }}
-        reason: Your organization requires reapproval when changes are made, so Graphite has dimissed approvals. See the output of `git range-diff` at ${{ env.WORKFLOW_RUN_URL}}
+        reason: Your organization requires reapproval when changes are made, so Graphite has dimissed approvals. ${{ (env.HAS_DIFF && join(['See the output of `git range-diff` at', env.WORKFLOW_RUN_URL], ' ')) || (env.NO_PREV_SHAS && join(['Could not find data on the previous version of this PR, see action logs at ', env.WORKFLOW_RUN_URL], ' ')) || join(['Failed to check if diff has changed, see action logs at ', env.WORKFLOW_RUN_URL], ' ') }}
 
     - name: Write SHAs to file
       shell: bash
